name: papyros
version: testing
label: PAPYROS_TESTING
packages:
    - mesa
    - mesa-vdpau
    - xf86-input-synaptics
    - xf86-video-ati
    - xf86-video-fbdev
    - xf86-video-intel
    - xf86-video-nouveau
    - xf86-video-openchrome
    - xf86-video-vesa
    - xf86-video-vmware
    - xorg-server
    - xorg-server-utils
    - sddm
    - xdg-app-git
    - qml-material-git
    - papyros-shell-git
    - papyros-settings-git
    - papyros-files-git
    - paper-icon-theme-git
    - liri-browser-git
    - liri-player-git
    - liri-vinyl-git
    - liri-calculator-git
    - networkmanager
    - pulseaudio
repos:
    papyros-testing: http://dash.papyros.io/repos/$repo/$arch
display_manager: sddm
files:
    sddm.conf: /etc/sddm.conf
