maintainer: Michael Spencer <sonrisesoftware@gmail.com>
name: papyros-appcenter
description: The App Center for Papyros
license: GPL
url: https://github.com/papyros/software-app
branch: master
type: cmake
depends:
    - qt5-base
    - qt5-declarative
    - qml-material-git
    - libpapyros-git
    - xdg-app-git
    - karchive
